# ======================================
# ModeManager Configuration
# ======================================
# Plugin Version: ${project.version}
# 
# This configuration file controls all aspects of the ModeManager plugin.
# For support or questions, visit: https://github.com/McKenzieJDan/ModeManager

# ======================================
# General Settings
# ======================================

# Master switch to enable or disable the plugin
enabled: true

# ======================================
# Mode Switching Settings
# ======================================

mode-switching:
  # Cooldown between mode switches (in seconds)
  cooldown-seconds: 30
  
  # Broadcast mode changes to all players
  broadcast-changes: false
  
  # Default mode to use when a player joins for the first time
  # Options: SURVIVAL, CREATIVE
  default-mode: SURVIVAL

# ======================================
# Protection Settings
# ======================================

protection:
  # Track blocks placed in creative mode to prevent mining them in survival
  track-creative-blocks: true
  
  # Track items placed in item frames in creative mode to prevent removing them in survival
  track-creative-item-frames: true
  
  # Prevent players from dropping items while in creative mode
  prevent-creative-drops: true
  
  # Prevent transferring items between modes via ender chests
  prevent-ender-chest-transfers: true
  
  # Prevent players from placing items in containers while in creative mode
  prevent-creative-container-placement: true
  
  # Prevent players from taking items from containers while in creative mode
  prevent-creative-container-taking: true
  
  # Prevent players from placing containers in creative mode
  prevent-creative-container-blocks: true
  
  # Prevent players from spawning mobs in creative mode
  prevent-creative-mob-spawning: true
  
  # Restricted entity types for mob spawning in creative mode
  # These entities cannot be spawned in creative mode
  # Set to "ALL" to restrict all entity types, or list specific types
  # For a list of valid entity types, see: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
  restricted-entity-types: "ALL"
  # Example of specific entity types:
  # restricted-entity-types:
  #   - ZOMBIE
  #   - SKELETON
  #   - CREEPER
  #   - VILLAGER
  #   - COW
  #   - PIG
  
  # Preserve creative inventory on death
  preserve-creative-inventory-on-death: true
  
  # Restrict usage of specific items in creative mode
  restrict-creative-items:
    # Enable or disable item restrictions in creative mode
    enabled: true
    
    # Bypass permission: modemanager.bypass.itemrestrictions
    
    # List of restricted items in creative mode
    # Format: MATERIAL_NAME or MATERIAL_NAME:DATA_VALUE
    # For a list of valid material names, see: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
    restricted-items:
      - LAVA_BUCKET
      - WATER_BUCKET
      - BUCKET
      - FLINT_AND_STEEL
      - TNT
      - TNT_MINECART
      - SPAWNER
      # Potions and related items
      - SPLASH_POTION
      - LINGERING_POTION
      - TIPPED_ARROW
      # Command blocks and structure blocks
      - COMMAND_BLOCK
      - CHAIN_COMMAND_BLOCK
      - REPEATING_COMMAND_BLOCK
      - COMMAND_BLOCK_MINECART
      - STRUCTURE_BLOCK
      - STRUCTURE_VOID
      - JIGSAW

# ======================================
# Inventory Management
# ======================================

inventories:
  # Save and restore armor contents when switching modes
  save-armor-contents: true
  
  # Save and restore offhand items when switching modes
  save-offhand-items: true
  
  # Use separate ender chest inventories for each mode
  separate-ender-chest: true
  
  # Clear inventory when switching to creative mode
  # This is a safety feature to prevent item duplication
  clear-on-creative: true

# ======================================
# Messages
# ======================================

messages:
  prefix: "&8[&eModeManager&8] "
  mode-changed: "&7Your gamemode has been changed to &e%mode%&7."
  mode-forced: "&7Your gamemode has been forced to &e%mode% &7by &e%admin%&7."
  mode-changed-broadcast: "&e%player% &7changed from &e%old_mode% &7to &e%mode%&7."
  already-in-mode: "&7You are already in &e%mode% &7mode."
  cooldown: "&7You must wait &f%time% &7seconds before changing modes again."
  no-permission: "&7You don't have permission to use this command."
  creative-drop-blocked: "&7You cannot drop items in creative mode."
  creative-block-protected: "&7This block was placed in creative mode and cannot be broken in survival."
  creative-item-frame-protected: "&7This item was placed in an item frame in creative mode and cannot be removed in survival."
  creative-container-blocked: "&7You cannot interact with containers in creative mode."
  creative-item-restricted: "&7You cannot use &e%item% &7in creative mode."
  creative-container-placement-blocked: "&7You cannot place containers in creative mode."
  creative-mob-spawning-blocked: "&7You cannot spawn mobs in creative mode."
  creative-spawn-egg-blocked: "&7You cannot use &e%entity% Spawn Egg &7in creative mode."
  inventory-restored: "&7Your &e%mode% &7inventory has been restored after death."
  player-only: "&7This command can only be used by players."
  player-not-found: "&7Player not found: &e%player%&7."
  invalid-mode: "&7Invalid game mode: &e%mode%&7. Only SURVIVAL and CREATIVE are supported."
  update-available: "&aA new update is available: &f%latest% &a(Current: &f%current%&a)"
  update-download: "&aDownload it at: &f%url%"
  potion-effects-cleared: "&7Your potion effects have been cleared when switching to survival mode."
  
  # Status command messages
  status-header: "&6Mode Status"
  status-current-mode: "&7Current mode: &e%mode%"
  status-cooldown-active: "&7Cooldown: &f%time% &7seconds"
  status-cooldown-ready: "&7Cooldown: &eReady"
  status-recent-changes: "&7Recent mode changes:"
  status-history-entry: "&7- %timestamp%: &e%mode% &7(%reason%)"
  
  # Admin command messages
  admin-usage: "&7Usage: &f/mode admin [list|check <player>|force <player> <mode> [reason]]"
  admin-check-usage: "&7Usage: &f/mode admin check <player>"
  admin-force-usage: "&7Usage: &f/mode admin force <player> <mode> [reason]"
  admin-unknown-command: "&7Unknown admin command. Use &f/mode admin [list|check <player>|force <player> <mode> [reason]]"
  
  admin-list-header: "&6Player Modes"
  admin-list-entry: "&e%player%&7: &e%mode%"
  
  admin-check-header: "&6Mode History for %player%"
  admin-check-current-mode: "&7Current mode: &e%mode%"
  admin-check-cooldown-active: "&7Cooldown: &f%time% &7seconds"
  admin-check-cooldown-ready: "&7Cooldown: &eReady"
  admin-check-history: "&7Mode history:"
  admin-check-history-entry: "&7- %timestamp%: &e%mode% &7(%reason%)"
  
  admin-force-success: "&7Forced &e%player% &7into &e%mode% &7mode."
  admin-force-failed: "&7Failed to force &e%player% &7into &e%mode% &7mode."
  
  # Help command messages
  help-header: "&6ModeManager Commands"
  help-survival: "&f/mode survival &7- Switch to survival mode"
  help-creative: "&f/mode creative &7- Switch to creative mode"
  help-status: "&f/mode status &7- Check your current mode and statistics"
  help-admin-list: "&f/mode admin list &7- List all players and their current modes"
  help-admin-check: "&f/mode admin check <player> &7- Check a specific player's mode history"
  help-admin-force: "&f/mode admin force <player> <mode> [reason] &7- Force a player into a specific mode"
  
  # Action bar messages configuration
  # Set to true for messages that should appear in the action bar instead of chat
  action-bar-messages:
    creative-drop-blocked: true
    creative-block-protected: true
    creative-item-frame-protected: true
    creative-container-blocked: true
    creative-item-restricted: true
    creative-container-placement-blocked: true
    creative-mob-spawning-blocked: true
    creative-spawn-egg-blocked: true
    inventory-restored: true
    potion-effects-cleared: true

# ======================================
# Update Checker Settings
# ======================================

update-checker:
  # Enable or disable the update checker
  enabled: true
  
  # The SpigotMC resource ID for the plugin
  # https://www.spigotmc.org/resources/modemanager.122976/
  resource-id: 122976
  
  # Notify admins when they join if an update is available
  notify-admins: true

# ======================================
# Advanced Settings
# ======================================

# Debug mode - when enabled, additional information will be printed to the console
# Only enable this when troubleshooting issues
debug: false