name: ModeManager
version: '${project.version}'
main: io.mckenz.modemanager.ModeManager
api-version: '1.21'
description: A plugin that allows players to switch between survival and creative modes while maintaining separate inventories.

commands:
  mode:
    description: Main command for ModeManager plugin
    usage: |
      /<command> survival - Switch to survival mode
      /<command> creative - Switch to creative mode
      /<command> status - Check your current mode and statistics
      /<command> admin list - List all players and their current modes
      /<command> admin check <player> - Check a specific player's mode history
      /<command> admin force <player> <mode> [reason] - Force a player into a specific mode
    aliases: [mm]

permissions:
  modemanager.admin:
    description: Gives access to all ModeManager admin commands
    default: op
    children:
      modemanager.use: true
      modemanager.creative: true
      modemanager.admin.list: true
      modemanager.admin.check: true
      modemanager.admin.force: true
      modemanager.reload: true
      modemanager.debug: true
      modemanager.update: true
      modemanager.bypass.itemrestrictions: true
      modemanager.bypass.containerplacement: true
  modemanager.use:
    description: Allows using mode switching
    default: true
  modemanager.creative:
    description: Allows access to creative mode
    default: op
  modemanager.admin.list:
    description: Allows listing all players and their current modes
    default: op
  modemanager.admin.check:
    description: Allows checking a specific player's mode history
    default: op
  modemanager.admin.force:
    description: Allows forcing a player into a specific mode
    default: op
  modemanager.reload:
    description: Allows reloading the plugin configuration
    default: op
  modemanager.debug:
    description: Allows toggling debug mode
    default: op
  modemanager.update:
    description: Allows receiving update notifications
    default: op
  modemanager.bypass.itemrestrictions:
    description: Allows bypassing item restrictions in creative mode
    default: op
  modemanager.bypass.containerplacement:
    description: Allows bypassing container placement restrictions in creative mode
    default: op