name: ModeManager
version: '${project.version}'
main: io.mckenz.modemanager.ModeManager
api-version: '1.21'
description: A template for Minecraft plugins

# TODO: Replace with your plugin commands
commands:
  modemanager:
    description: Main command for ModeManager plugin
    usage: |
      /<command> status - Shows plugin status
      /<command> toggle - Enable/disable the plugin
      /<command> reload - Reload the configuration
      /<command> debug - Toggle debug mode
    aliases: [mm]

# TODO: Replace with your plugin permissions
permissions:
  modemanager.admin:
    description: Gives access to all ModeManager commands
    default: op
    children:
      modemanager.status: true
      modemanager.toggle: true
      modemanager.reload: true
      modemanager.debug: true
      modemanager.update: true
  modemanager.status:
    description: Allows checking the plugin status
    default: op
  modemanager.toggle:
    description: Allows enabling/disabling the plugin
    default: op
  modemanager.reload:
    description: Allows reloading the plugin configuration
    default: op
  modemanager.debug:
    description: Allows toggling debug mode
    default: op
  modemanager.update:
    description: Allows receiving update notifications
    default: op